version: '3.4'

services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    php:
        build:
            context: docker/php7-fpm
            target: php_base
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - cache:/var/www/symfony/var/cache
            - vendor:/var/www/symfony/vendor
        depends_on:
            - db
        env_file:
            - .env
        environment:
            APP_ENV: dev
    nginx:
        image: nginx:alpine
        working_dir: /var/www/symfony
        volumes:
            - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
        ports:
            - "8080:80"
        depends_on:
            - php

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            PMA_HOST: ${DATABASE_HOST}
        ports:
         - "8081:80"
        depends_on:
            - db
volumes:
    cache:
    vendor:
