version: '3'

services:
    db:
        image: mariadb:10.1.44
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    php:
        build: docker/php7-fpm
        volumes:
            - ./:/var/www
            - ${HOME}/.composer:/root/.composer
        depends_on:
            - db
            - mail
        env_file:
            - .env
        environment:
            APP_ENV: dev
            MAILER_URL: smtp://mail:1025
            CDN_PATH: http://localhost:8080/uploads/media
            BEHAT_PARAMS: '{"extensions" : {"Alex\\MailCatcher\\Behat\\MailCatcherExtension\\Extension" : {"url" : "http://mail:1080"}}}'
    nginx:
        image: nginx:alpine
        working_dir: /var/www
        volumes:
            - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
            - ./var/logs/nginx/:/var/log/nginx
        ports:
            - "8080:80"
        depends_on:
            - php

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            PMA_HOST: ${DATABASE_HOST}
        ports:
         - "8081:80"
        depends_on:
            - db
    mail: # watch mails on: http://localhost:1080
        image: schickling/mailcatcher
        ports:
          - "1080:1080"
