api_platform:
  eager_loading:
    enabled: false
  allow_plain_identifiers: true
  path_segment_name_generator: api_platform.path_segment_name_generator.dash
  default_operation_path_resolver: api_platform.operation_path_resolver.dash
  name_converter: App\Serializer\NameConverter\SnakeCaseToDasherizedNameConverter
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
  formats:
    jsonapi: [application/vnd.api+json]
    #        yaml: [application/x-yaml]
    html: [text/html]
  error_formats:
    jsonapi: [application/vnd.api+json]

  collection:
    pagination:
      enabled: false

  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [ 3 ]