name: CD

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  start_deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot-preview[bot]'
    steps:
      - uses: avakar/create-deployment@v1
        if: github.ref == 'refs/heads/develop'
        with:
          ref: ${{ github.ref }}
          environment: staging
          required_contexts: ''
          auto_merge: false
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - uses: avakar/create-deployment@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          ref: ${{ github.ref }}
          environment: production
          required_contexts: ''
          auto_merge: false
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}